### ISSUE TITLE
Issue in connecting filebeat to graylog

### ISSUE THREAD

**Issue by abhatt4** [sivasamyk/graylog2-input-lumberjack#5]
Hi,

I got this exception on the graylog-server logs after doing the said changes.

0 WARN  [LumberjackServer] Exception while creating channel pipeline
java.io.FileNotFoundException: admin (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.

am using filebeat 1.1.1 to send the logs, to graylog server with following output defined,

logstash:
    # The Logstash hosts
    hosts: ["X.X.XX.X:5044"]

I have configured the plugin and have defined the input as beat listening to 5044 port.

On the graylog server i have 

graylog-server 1.3.3
graylog-web 1.3.3
elasticsearch 1.7.3.

Do i have to do any other change on the graylog server side. I did what was written in here. Help will be appreciated.

**Comment by abhatt4** [comment]
Wrong plugin closing it
